name: envify
description: A better way to handle environment variables using `.env` file.
version: 2.0.3
homepage: https://github.com/MithrilTechnologies/envify

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  lint: ^2.1.2
  test: ^1.24.2

scripts: ../derry.yaml
