name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 2.0.3
homepage: https://github.com/MithrilTechnologies/envify

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  build: ^2.3.1
  dotenv: ^4.0.1
  path: ^1.8.2
  source_gen: ^1.2.5
  envify:
    git:
      url: https://github.com/MithrilTechnologies/envify.git
      path: envify

dev_dependencies:
  lint: ^1.10.0
  source_gen_test: ^1.0.0
  test: ^1.16.8

scripts: ../derry.yaml
