name: envify_generator
description: Code generator for envify, a better tool to handle environment variables.
version: 2.0.3
homepage: https://github.com/MithrilTechnologies/envify

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^5.12.0
  build: ^2.4.0
  dotenv: ^4.1.0
  path: ^1.8.3
  source_gen: ^1.3.2
  envify:
    git:
      url: https://github.com/MithrilTechnologies/envify.git
      path: envify

dev_dependencies:
  lint: ^2.1.2
  source_gen_test: ^1.0.5
  test: ^1.24.2

scripts: ../derry.yaml
